### ISSUE TITLE
BigDecimal work plan

### ISSUE THREAD

**Issue by littledan** [littledan/proposal-bigdecimal#45]
We plan to present BigDecimal for Stage 1 at the February 2020 TC39 meeting. To get to Stage 2, it will be useful to accomplish the following tasks:
- [ ] Write complete reference documentation with examples for BigDecimal
- [ ] Write BigDecimal spec text
- [ ] Implement a JSBI-style polyfill (#17)
- [ ] Implement BigDecimal literal syntax in Babel (#18)
- [ ] Wrap the JSBD polyfill in a style using the operator overloading proposal
- [ ] Write some larger, more realistic code samples (#34)
- [ ] Scrub all bugs about semantic questions and ensure that we have good, initial answers
- [ ] Survey use cases and environment interactions more thoroughly and document results
- [ ] Determine which rounding modes and standard library functions to include

I plan to work on these, but there's a lot to do, and I could use help. If you want to get involved, feel free to respond to this issue; we can use it to coordinate task ownership.

**Comment by hildjj** [comment]
I've tagged the implementation bugs with pointers to [bignumber.js](https://github.com/MikeMcl/bignumber.js), which may have a lot of what you need to get started.

**Comment by softboy99** [comment]
What's the status of the progress? When we can go to stage3?

**Comment by jessealama** [comment]
> What's the status of the progress? When we can go to stage3?

We're still at stage 1. Stage 2 is possible this year, but probably not stage 3.

**Comment by jessealama** [comment]
I think we can close this issue. We've nailed down quite a lot since 2020 and the current iteration of the proposal is essential complete. References to a polyfill or Babel are obsolete since we currently do not propose new syntax. But if I'm missing something that might really help spread the word about decimal and make things easier for proposal reviews, fans, critics, and passer-by to make sense of the proposal, please let me know.

**Comment by softboy99** [comment]
I'm very disappointed with this proposal. Almost more than 10 years past. it is still in discussion. And the current result without any business value

**Comment by softboy99** [comment]
> > What's the status of the progress? When we can go to stage3?
> 
> We're still at stage 1. Stage 2 is possible this year, but probably not stage 3.

Hi, @jessealama 
Now is 2026, it's still in stage 1, why?

**Comment by ljharb** [comment]
There's multiple reasons, but one of them is that browsers won't agree to add new primitives, and some delegates (myself, at least) believe that something as foundational as numbers must not exist except as primitives.

**Comment by migueldecimal128** [comment]
> but one of them is that browsers won't agree to add new primitives, 

Pls say more about this. Don't want to increase memory footprint? Don't want to build/support?

**Comment by softboy99** [comment]
> There's multiple reasons, but one of them is that browsers won't agree to add new primitives, and some delegates (myself, at least) believe that something as foundational as numbers must not exist except as primitives.

If it's true. why goes to stage 1. It should killed at stage 0. Wasting of time!!!!

**Comment by ljharb** [comment]
@softboy99 The purpose of stage 1 is to explore the problem space, which is what we're doing.

@migueldecimal128 my limited understanding of their position is that the effort required to implement a new primitive, in a way that won't impact performance of existing code, is something they deem not "worth it" for the benefit of the feature.
